version: '3.8'

services:
  postgres:
    container_name: jobapp-postgres
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: new_employee_db
    ports:
      - "6634:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    container_name: jobapp-backend
    build:
      context: ./Backend
    ports:
      - "3075:3075"
    environment:
      PG_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: admin123
      DB_NAME: new_employee_db
    depends_on:
      - postgres
    volumes:
      - ./Backend/Uploads:/app/Uploads
    restart: unless-stopped

  frontend:
    container_name: jobapp-frontend
    build:
      context: ./Frontend
    ports:
      - "8205:80"
    depends_on:
      - backend
    restart: unless-stopped

  hr_page:
    container_name: jobapp-hrpage
    build:
      context: ./HR_Page
    ports:
      - "8206:80"
    depends_on:
      - backend
    restart: unless-stopped

  offer_letter:
    container_name: jobapp-offerletter
    build:
      context: ./Offer_letter
    ports:
      - "8207:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
